#24 Update doguctl to 0.13.1
cloudogu/base-debian pull request #26
Opened 2024-12-27 09:28 UTC by ppxl

This PR closes #24 by updating doguctl to a newer version without CVE-2024-45337

This change moves the doguctl binary away from ${projectDir}/usr/bin to `${projectDir}/packages` where git will ignore any tar.gz files. This is done to avoid commits with doguctl binaries, knowingly that this will increase the container image by ~15 MB.

This increase is accepted by gaining a similar container creation process as well as similar directory layout compared to the alpine base image repository.

2025-01-02 08:43 UTC, kahoona77 requested changes

2025-01-02 08:43 UTC, kahoona77 commented on CHANGELOG.md
> +## [12.7-2] - 2024-
```suggestion
## [12.7-2] - 2024-09-23
```

2025-01-02 08:43 UTC, kahoona77 commented on Dockerfile
>  COPY resources/usr/bin/doguctl-$DOGUCTL_VERSION.tar.gz /packages
```suggestion
COPY packages/doguctl-$DOGUCTL_VERSION.tar.gz /packages
```

And maybe we need to restructure the Dockerfile, because Docker always uses the cache when building this stage, even if the checksum or the doguctl-file is changed.
So the verification does not work.

2025-01-06 08:27 UTC, ppxl commented on CHANGELOG.md
> +## [12.7-2] - 2024-
Oops, started and got sidetracked. :+1:

2025-01-06 08:30 UTC, ppxl commented on Dockerfile
>  COPY resources/usr/bin/doguctl-$DOGUCTL_VERSION.tar.gz /packages
Ugh, this is indeed a creepy feature. The verification should work every time as you said. T_T

2025-01-06 10:43 UTC, ppxl commented on Dockerfile
>  COPY resources/usr/bin/doguctl-$DOGUCTL_VERSION.tar.gz /packages
The problem here is the unreferenced stage `doguctlbinaryverify`. `docker buildx` will optimize unreferenced stages away. I am going to fix this by calling the stage manually within `make build`

2025-01-06 14:51 UTC, kahoona77 approved these changes
LGTM

2025-01-06 14:52 UTC, merged